### ISSUE TITLE
Should we use short or long names for derived elements?

### ISSUE THREAD

**Issue by rehno-lindeque** [circuithub/elm-html-shorthand#1]
For example, &lt;a&gt; and &lt;button&gt; has the idiomatic forms:

``` elm
a' : UrlString -> TextString -> Html
button' : TextString -> Signal.Message -> Html
```

should a "button" link (an anchor turned into a button via the `onClick` event) look like:

``` elm
aButton' : TextString -> Signal.Message -> Html
```

or

``` elm
buttonLink' : TextString -> Signal.Message -> Html
```

or even one of these?

``` elm
a'button : TextString -> Signal.Message -> Html
button'link : TextString -> Signal.Message -> Html
```

---

Similarly &lt;input&gt; has several possible idiomatic [forms](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Attributes):

``` elm
inputField' : FieldUpdate -> Html
inputRadio' : FieldUpdate -> Html
inputCheckbox' : FieldUpdate -> Html
```

or

``` elm
field' : FieldUpdate -> Html
radio' : FieldUpdate -> Html
checkbox' : FieldUpdate -> Html
```

or

``` elm
input'field : FieldUpdate -> Html
input'radio : FieldUpdate -> Html
input'checkbox : FieldUpdate -> Html
```

---

Note that all of these would all have classy forms also:

``` elm
aButtonc : TextString -> Signal.Message -> Html -- possibly buttonLinkc
inputFieldc : FieldUpdate -> Html
inputRadioc : FieldUpdate -> Html
inputCheckboxc : FieldUpdate -> Html
```

versus

``` elm
buttonlinkc : TextString -> Signal.Message -> Html
fieldc : FieldUpdate -> Html
radioc : FieldUpdate -> Html
checkboxc : FieldUpdate -> Html
```

versus

``` elm
acbutton : TextString -> Signal.Message -> Html
inputcfield : FieldUpdate -> Html
inputcradio : FieldUpdate -> Html
inputccheckbox : FieldUpdate -> Html
```

**Comment by rehno-lindeque** [comment]
On &lt;button&gt; and &lt;a&gt;, it would be nice if we could do something like [clickable](http://package.elm-lang.org/packages/elm-lang/core/1.0.0/Graphics-Input#clickable) that could be applied directly to `a'` or any other element instead - but I haven't yet thought of a strategy for implement this in a simple way. Unfortunately it doesn't seem as though `Html` is as easily modifiable as `Element` is at the moment.

Note that `radio'`, `checkbox'` and `field'` would probably remain for discussion even if we implement the above.

**Comment by rehno-lindeque** [comment]
Also see `submitButton` and `resetButton` which currently exist and may change as a result of this.

**Comment by Apanatshka** [comment]
I dislike primes in the middle of names. It just looks off to me. I'm leaning towards the short names. 
If you want to be explicit about some of these being `<input>` you can create a Shorthand.Input module for these specialised functions and people can decide to import them unqualified or qualified as Input or Shorthand.

**Comment by rehno-lindeque** [comment]
I'm also not fond of primes inside names, I agree with you. Let's forget about those. (c's in the middle of the names end up even more confusing)
