### ISSUE TITLE
Version 10.0.0 publishing 

### ISSUE THREAD

**Issue by aluuu** [circuithub/elm-html-shorthand#10]
Hello, @rehno-lindeque.

Looks like version 10.0.0 has not been published yet, but it appears in [elm-bootstrap-html](https://github.com/circuithub/elm-bootstrap-html/blob/6.3.4/elm-package.json#L14) dependencies.

BTW, I think it would be better if new version should be lower than 10.0.0, because there's no major API changes, as I see.

**Comment by aluuu** [comment]
Also, another one reason to leave version lower then 10.0.0 is common dependency usage.
I assume, that majority of the library users have `9.0.0 <= v < 10.0.0` in their `elm-package.json` files, so they don't even notice this update if version would stay under 10.0.0.

**Comment by rehno-lindeque** [comment]
Hmm, pretty sure @agrafix made that bump. But aren't version bumps completely managed by `elm package bump`? In fact, in the past you couldn't publish if the versions didn't correspond to whatever `elm package` determines to be the next correct version.

What do you think @agrafix ?

**Comment by agrafix** [comment]
The major bump was needed because the API changed. (`EventDecodeError` lost it's phantom parameter for now as they are unsupported for `type alias`es. ) I will publish 10.0.0 now

**Comment by agrafix** [comment]
Done.

**Comment by rehno-lindeque** [comment]
Nice, thanks!
