### ISSUE TITLE
Elm 0.17 upgrade?

### ISSUE THREAD

**Issue by stkb** [circuithub/elm-html-shorthand#11]
Just wondered if a 0.17 update was being worked on

**Comment by rehno-lindeque** [comment]
We haven't got round to upgrading to 0.17 yet, sorry. If you are willing to upgrade and publish yourself, I'd be happy to give you commit rights to this repo. Note that elm-html-extra (a dependency of this package) has a new home at elm-community/html-extra.

**Comment by stkb** [comment]
Thanks. I'll start working on it, though I might have some questions.

**Comment by stkb** [comment]
Just a note that I'm still working on this, and will submit a PR probably tomorrow, though it will still be a bit WIP

**Comment by rehno-lindeque** [comment]
I'd be happy to take a look once you're ready. The trickiest bits are likely to be event (signal) handling and decoding - hope that's not turning out to be tough.

**Comment by stkb** [comment]
@rehno-lindeque PR is now up at #12 :)
