### ISSUE TITLE
encodeClass issues

### ISSUE THREAD

**Issue by gyzerok** [circuithub/elm-html-shorthand#7]
All the classes are converted to lower case with your package which seems my styles not to work correctly.

I use upper-case letters in my classes because I use [BEM methodology](https://en.bem.info/).

**Comment by gyzerok** [comment]
The other thing is I'm adding some modificators like `_modificator` which seems also not to work.

**Comment by gyzerok** [comment]
I guess a better solution here is to pass `class` as is without encoding to not confuse the developer with unexpected behaviour.

P.S.: I think same should be done with `id`.

**Comment by rehno-lindeque** [comment]
Shorthand was intended to be somewhat opinionated and constrained in terms of the conventions it supports. I agree that there's some trade-off with the unexpected reformatting.

Unfortunately I'm not familiar with BEM and I'm not very active with Elm at the moment either; How about forking the project and doing a shorthand that enforces the BEM conventions? I'd be curious to see what that looks like.

**Comment by gyzerok** [comment]
@rehno-lindeque its easy to fork a project and publish a new package (I've already done all the fixes in `elm-stuff` to fix my issues). But I don't want to make elm package manager to be similar to npm with a lot of the same packages. What do you think about a PR? I can do one easily.

**Comment by rehno-lindeque** [comment]
Hmm, ok, I'd say submit a PR to look at. I think we might still want to check that anything illegal is filtered out of the identifiers but from what I remember that's not very much these days.
